### PR TITLE
Initial set of parquet utilities (i.e. csv2pq).

### PR DESCRIPTION
**Pull request by abh3**
Please review.

### CODE REVIEW

**Comment by andy-slac** [comment]
One general comment - the structure python/ folder needs to be fixed, it needs more sub-packages, you are not supposed to put you modules inside lsst top-level package. Actually, I don't quite understand hot it works at all, it looks like you are importing your modules directly as `import csv2pq_utils`, do you set PYTHONPATH somehow to point inside lsst/ folder?

**Comment by andy-slac** [comment]
Sorry for closing/reopening, clicked wrong button.

**Comment by abh3** [comment]
I was following, as best I could, other python packages in the repo. There really isn't one that implements an interactive cli interface that I found, so it's pretty much shooting in the ark. I don't know how all of this gets installed other than the python/lsst modules seem to be installed in a standard llst directory for python modules. Of course, I can be totally off-base as it's not exactly obvious to me.

**Comment by andy-slac** [comment]
I think there should be plenty of examples of Python CLI in LSST, though many of those could be somewhat complicated. I just searched for `argparse` in LSST code and one package that may be a good example for you is https://github.com/lsst/validate_drp, https://github.com/lsst/validate_drp/blob/master/bin.src/reportPerformance.py is a simple example for `argparse` use.

Regular LSST packages are installed with scons/sconsUtils, which I think you would like to avoid. That means that you need to configure/install it yourself (I guess with setup.py). If you can describe installation and usage (including how to import your Python module) briefly in your README it would help us understand how to better structure your source. Or you can reconsider and stick to sconsUtils in which case the structure should also be similar to other LSST packages.

**Comment by abh3** [comment]
The package in this repo has been moved to lsst_dm and is no longer applicable here. In fact, this repo should be deleted.

**Pull request closed without merging**
